import { jsonToSchema } from "@walmartlabs/json-to-simple-graphql-schema/lib";
import { buildSchema } from "graphql";
const generateSchema = (json) => {
  const schema = jsonToSchema({ jsonInput: JSON.stringify(json) });
  return schema;
};

export const generateGraphQL = (data) => {
  const schemaRaw = generateSchema(data).value.replace(
    "AutogeneratedMainType",
    "Scraps"
  );
  const queries = `
      type Query {
          scraps: Scraps
      }
      `;
  const schema = buildSchema(schemaRaw + queries);
  const root = { scraps: () => data };
  return {
    schema,
    root,
  };
};
